mobile_detect:
  redirect:
    full :
      is_enabled: true            # default false
        status_code: 301            # default 302
        action: redirect
    mobile:
      is_enabled: true
      status_code: 301
      action: redirect
    tablet:
      is_enabled: true            # default false
      status_code: 301            # default 302
      action: redirect
  switch_device_view: ~
#       detect_tablet_as_mobile: true
