mobile_detect:
  redirect:
    full :
      is_enabled: true            # default false
        host: http://site.com       # with scheme (http|https), default null, url validate
        status_code: 301            # default 302
        action: redirect
    mobile:
      is_enabled: true
      host: http://m.site.com
      status_code: 301
      action: redirect
    tablet: ~
  switch_device_view: ~