swiftmailer:
  transport:        smtp
  host:             smtp.gmail.com
  port:             587
  encryption:       tls
  auth-mode:        login
  username:         contact@in-memoriae.fr
  password:         inmemoriaecontact
  spool: { type: 'memory' }
